### ISSUE TITLE
OS X binary throws error at start

### ISSUE THREAD

**Issue by priyadarshan** [borodust/notalone#2]
Hello,

Launching `notalone` version 1.1.5 on OS X 10.10 throws,

```
$ /Users/priyadarshan/bin/notalone/notalone
Signal 13 masked
fatal error encountered in SBCL pid 33752(tid 0xb0087000):
some deferrable signals blocked, some unblocked
```

I also tried version 1.1.0 with exact same error message.

**Comment by borodust** [comment]
Thanks much for the report!
Most likely related to https://github.com/borodust/trivial-gamekit/issues/15

**Comment by priyadarshan** [comment]
Thank you, I will watch that ticket as well. I cannot test much trivial-gamekit, that is why I was relying on binary.Thanks for both!

**Comment by borodust** [comment]
By the way, do you happen to use macos with retina display?

**Comment by priyadarshan** [comment]
No, I am testing it on Mac mini, OS X 10.10, with 1920x1200 Eizo display.

**Comment by priyadarshan** [comment]
As off-topic, (but I could open a ticket if you wish), I would be glad to test on FreeBSD workstations as well, if I could have a little help while locating necessary Linux libraries. FreeBSD can run basically all Linux software, only uncommon libraries needs to be installed manually.

**Comment by borodust** [comment]
I would gladly accept contributions, but porting `trivial-gamekit`to an unsupported platform is quite an involved process. You would need to prepare dynamic libraries and make a `cl-autowrap` `.spec` files for each of those libraries. For making a `.spec` file you would need to build [`c2ffi`](https://github.com/rpav/c2ffi/) project with llvm/clang developer libraries (which means you possibly need to build those yourself too).

**Comment by priyadarshan** [comment]
Wow, that sounds like a bit out of my depth. I will continue testing on OS X for now.

PS: As far as I know, ASDF 3.3 was supposed to be able to help include libraries in the distributable binary: https://github.com/fare/asdf2017/
I wish there would be some tutorial around.

**Comment by borodust** [comment]
Should be fixed now. Please, check if latest [macOS archive](https://github.com/borodust/notalone/releases/download/v1.1.6/notalone-x86-64-osx-v1.1.6.zip) works for you, and let me know if there any issues left.

**Comment by borodust** [comment]
Apparently, it is followed by another _bug_ I'm going to fix tomorrow, but archive I linked earlier still could work for you. Give it a go :)

**Comment by borodust** [comment]
Bug fixed. Please, check out [this](https://github.com/borodust/notalone/releases/tag/v1.1.7) latest release.

**Comment by priyadarshan** [comment]
I have downloaded v 1.1.7, but still having an error, although slightly different:

```
# ll
total 35848
drwxr-xr-x   5 priyadarshan  staff   170B  7 Dec 08:08 assets
drwxr-xr-x  15 priyadarshan  staff   510B  7 Dec 08:08 lib
-rwxr-xr-x   1 priyadarshan  staff    18M  7 Dec 08:08 notalone
# ./notalone
fatal error encountered in SBCL pid 15576(tid 0xb0087000):
deferrable signals partially blocked: {}
```

I tried the Windows version, using Vmware, and that works fine.

It could be that I am using OS X 10.10? At the moment I cannot upgrade to 10.13, but I could try in a month or so. 

By the way, the game is simple but quite charming.

I like it very much.

Thank you!

**Comment by borodust** [comment]
Yeah, it's weird. Maybe 10.10 issue after all, I'm not sure. 

I'm glad you liked it!

**Comment by priyadarshan** [comment]
I will test it on OS Sierra when I have the chance (perhaps I will install it on Virtual Box).
The only problem with `notalone` is that it is addictive.

**Comment by analyticd** [comment]
Hi Borodust, I am having what appears to be a different error but still results in the game failing at startup after being loaded and started as per your github readme page (via quicklisp). I am on macOS Sierra. Here is the stack trace from slime:

```
The value #<Unknown Arguments> is not of the expected type LIST.
   [Condition of type TYPE-ERROR]

Restarts:
 0: [CONTINUE] Skip flow block returning nil
 1: [USE-VALUE] Skip flow block returning provided value
 2: [CONTINUE] Skip flow block returning nil
 3: [USE-VALUE] Skip flow block returning provided value
 4: [ABORT-BREAK] Reset this thread
 5: [ABORT] Kill this thread

Backtrace:
  0: (#<STANDARD-METHOD DISSECT:PRESENT-OBJECT (DISSECT:CALL T)> #<CCL-CALL [5] NIL> #<STRING-OUTPUT-STREAM  #x302003A5E89D>)
      Locals:
        CALL = #<CCL-CALL [5] NIL>
        STREAM = #<STRING-OUTPUT-STREAM  #x302003A33A8D>
        *PRINT-PRETTY* = NIL
        *PRINT-READABLY* = NIL
        #:LOOP-LIST-19802 = #<Unknown Arguments>
        ARG = NIL
        #:LOOP-LIST-HEAD-19803 = (NIL)
        #:LOOP-LIST-TAIL-19804 = (NIL)
  1: (#<STANDARD-METHOD DISSECT:PRESENT-OBJECT (LIST T)> (#<CCL-CALL [0] DEFAULT-INITARGS | /usr/local/Cellar/clozure-cl/1.11/libexec/level-1/l1-clos-boot.lisp:2703> ..)) (NIL))
      Locals:
        LIST = (#<CCL-CALL [0] DEFAULT-INITARGS | /usr/local/Cellar/clozure-cl/1.11/libexec/level-1/l1-clos-boot.lisp:2703> ..))
        STREAM = (NIL)
        #:G19542 = #<CCL-CALL [0] DEFAULT-INITARGS | /usr/local/Cellar/clozure-cl/1.11/libexec/level-1/l1-clos-boot.lisp:2703>
        ITEM = NIL
        #:LOOP-LIST-19544 = #<Unknown Arguments>
  2: (NIL #<Unknown Arguments>)
      [No Locals]
  3: ((:INTERNAL CL-BODGE.UTILS::INVOKE-BODGY))
      Locals:
        STREAM = #<STRING-OUTPUT-STREAM  #x302003A33A8D>
        #:COMPILER-VAR = (NIL)
        E = #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>
  4: (SIGNAL #<CCL::UNDEFINED-FUNCTION-CALL #x302003A5FF2D>)
      Locals:
        CONDITION = #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>
        CCL::ARGS = NIL
        CCL::%HANDLERS% = ((PROCESS-RESET))
        CCL::TAG = (WARNING #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CL-BODGE.UTILS::INVOKE-BODGY) #x302002E279DF> T #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CL-BODGE.UTILS::INVOKE-BODGY) #x302002E2799F>)
        CCL::HANDLERS = (T #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CL-BODGE.UTILS::INVOKE-BODGY) #x302002E2799F>)
        CCL::FN = #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CL-BODGE.UTILS::INVOKE-BODGY) #x302002E2799F>
  5: (CCL::%ERROR #<CCL::UNDEFINED-FUNCTION-CALL #x302003A5FF2D> NIL 10242206)
      Locals:
        CONDITION = #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>
        ARGS = NIL
        ERROR-POINTER = 10242206
  6: (CCL::DEFAULT-UNDEFINED-FUNCTION-CALL-RESTARTS 10242206 X86-DARWIN64::|memcpy| (#<A Foreign Pointer #x198FB34> #<A Foreign Pointer #x32800018> 12))
      Locals:
        FRAME-PTR = 10242206
        FUNCTION-NAME = X86-DARWIN64::|memcpy|
        ARGS = (#<A Foreign Pointer #x198FB34> #<A Foreign Pointer #x32800018> 12)
        CONDITION = #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>
        OTHER-FUNCTIONS = NIL
        #:STORE-VALUE = #<RESTART STORE-VALUE #x4F46C1D>
        #:USE-VALUE = #<RESTART USE-VALUE #x4F46BCD>
        #:USE-HOMONYM = #<RESTART CCL::USE-HOMONYM #x4F46B7D>
        #:CONTINUE = #<RESTART CONTINUE #x4F46B2D>
        #:G164472 = (#<RESTART CONTINUE #x4F46B2D> #<RESTART CCL::USE-HOMONYM #x4F46B7D> #<RESTART USE-VALUE #x4F46BCD> #<RESTART STORE-VALUE #x4F46C1D>)
        %RESTARTS% = ((#<RESTART CONTINUE #x4F46B2D> #<RESTART CCL::USE-HOMONYM #x4F46B7D> #<RESTART USE-VALUE #x4F46BCD> #<RESTART STORE-VALUE #x4F46C1D>) ..)))
        #:G164473 = #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>
        *CONDITION-RESTARTS* = ((#<RESTART STORE-VALUE #x4F46C1D> . #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>) (#<RESTART USE-VALUE #x4F46BCD> . #<CCL::UNDEFINED-FUNCTION-CALL #x302003A33FAD>) ..)))
  7: (CCL::HANDLE-UDF-CALL #<A Foreign Pointer #x700003BE5880> 10242206)
      Locals:
        XP = #<A Foreign Pointer #x700003BE5880>
        FRAME-PTR = 10242206
        ARGS = (#<A Foreign Pointer #x198FB34> #<A Foreign Pointer #x32800018> 12)
  8: ((:INTERNAL CCL::%XERR-DISP))
      Locals:
        FRAME-PTR = 10242206
        FN = #<Compiled-function BODGE-SNDFILE::REPLACE-FOREIGN-MEMORY #x302001EEC29F>
        OP0 = 205
        OP1 = 199
        OP2 = 0
        SKIP = 2
        XP = #<A Foreign Pointer #x700003BE5880>
        XCF = #<A Foreign Pointer #x4E244F0>
  9: (CCL::FUNCALL-WITH-ERROR-REENTRY-DETECTION #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%XERR-DISP) #x4F46C6F>)
      Locals:
        THUNK = #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%XERR-DISP) #x4F46C6F>
        COUNT = 0
        *ERROR-REENTRY-COUNT* = 0
 10: (CCL::%XERR-DISP 15393170639450)
      Locals:
        #:G166646 = 15393170639450
        #:G166655 = #<A Foreign Pointer [stack-allocated] #x700003BE52D0>
        XP = #<A Foreign Pointer #x700003BE5880>
        XCF = #<A Foreign Pointer #x4E244F0>
        #:G166656 = #<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%XERR-DISP) #x4F46C6F>
 11: (CCL::%PASCAL-FUNCTIONS% 2 15393170639450)
      Locals:
        INDEX = 2
        ARGS-PTR-FIXNUM = 15393170639450
        LISP-FUNCTION = #<Compiled-function CCL::%XERR-DISP (Non-Global)  #x3000005C286F>
        WITHOUT-INTERRUPTS = NIL
        *CALLBACK-TRACE-P* = NIL
 12: (NIL #<Unknown Arguments>)
      [No Locals]
 13: (BODGE-SNDFILE::REPLACE-FOREIGN-MEMORY #<A Foreign Pointer #x32800018> #<A Foreign Pointer #x198FB34> 12)
      Locals:
        SRC = #<A Foreign Pointer #x32800018>
        DST = #<A Foreign Pointer #x198FB34>
        COUNT = 12
        LENGTH = 12
 14: (CFFI-CALLBACKS::|BODGE-SNDFILE::VIO-READ| 15393170639732)
      Locals:
        #:G66399 = 15393170639732
        #:G66408 = 12
        BODGE-AUTOWRAP:PTR = #<A Foreign Pointer #x198FB34>
        COMMON-LISP:COUNT = 12
        BODGE-SNDFILE::USER-DATA = #<A Null Foreign Pointer>
 15: (CCL::%PASCAL-FUNCTIONS% 14 15393170639732)
      Locals:
        INDEX = 14
        ARGS-PTR-FIXNUM = 15393170639732
        LISP-FUNCTION = #<Compiled-function CFFI-CALLBACKS::|BODGE-SNDFILE::VIO-READ| (Non-Global)  #x302001EEB3BF>
        WITHOUT-INTERRUPTS = NIL
        *CALLBACK-TRACE-P* = NIL
 16: (NIL #<Unknown Arguments>)
      [No Locals]
 17: (%SNDFILE:OPEN-VIRTUAL #<VIRTUAL-IO {#X0076C0E0}> 16 #<INFO {#X0073AF90}> #<A Null Foreign Pointer>)
      Locals:
        SFVIRTUAL = #<VIRTUAL-IO {#X0076C0E0}>
        MODE = 16
        SFINFO = #<INFO {#X0073AF90}>
        USER-DATA = #<A Null Foreign Pointer>
        #:SFVIRTUAL65100 = #<A Foreign Pointer #x76C0E0>
        #:SFINFO65102 = #<A Foreign Pointer #x73AF90>
        #:USER-DATA65103 = #<A Null Foreign Pointer>
 18: (#<STANDARD-METHOD CL-BODGE.RESOURCES:DECODE-RESOURCE (CL-BODGE.RESOURCES::AUDIO-RESOURCE-HANDLER T)> #<CL-BODGE.RESOURCES::AUDIO-RESOURCE-HANDLER #x302002DA05AD> #<BASIC-FILE-BINARY-INPUT-STREAM ("/U..
      Locals:
        THIS = #<CL-BODGE.RESOURCES::AUDIO-RESOURCE-HANDLER #x302002DA05AD>
        STREAM = #<BASIC-FILE-BINARY-INPUT-STREAM ("/Users/lriley/quicklisp/dists/org.borodust.bodge/software/notalone-20171216201731/assets/sounds/Orbital_Colossus.ogg"/10 ISO-8859-1) #x302002E1F87D>
        BODGE-SNDFILE::*VIRTUAL-FILE* = #S(BODGE-SNDFILE::VIRTUAL-FILE :DATA #(79 103 103 83 0 2 ...) :MAX-POSITION 0 :POSITION ...)
        #:VIRTUAL-IO103685 = #<VIRTUAL-IO {#X0076C0E0}>
        #:TMP103689 = #<INFO {#X0073AF90}>
        #:HANDLE103698 = #<A Null Foreign Pointer>
 19: (CL-BODGE.RESOURCES:LOAD-RESOURCE #P"/_asset/NOTALONE/ORBITAL-COLOSSUS")
 --more--

```

**Comment by borodust** [comment]
@analyticd That's a different issue. Let's discuss it in https://github.com/borodust/notalone/issues/3

**Comment by analyticd** [comment]
Ok, will do.

**Comment by borodust** [comment]
@priyadarshan any luck?

**Comment by priyadarshan** [comment]
Sorry for tardy reply, High Sierra is breaking so many apps on my physical mac that I had to revert to 10.11. So, I have now High Sierra running as a VM with VirtualBox on FreeBSD.

Starting latest available binary for osx (1.2.0), I get

```
priyadarshans-iMac:notalone priyadarshan$ ./notalone 
<ERROR> [15:06:28] cl-bodge.utils utils.lisp (invoke-bodgy h1) -
  Unhandled error:
NSGL: Failed to find a suitable pixel format
   [Condition of type SIMPLE-ERROR]

#<ENVIRONMENT {10057E1D33}>
   [Environment of thread #<THREAD "main thread" RUNNING {1003520083}>]

Available restarts:
 0: [STOP] Stop the task.
 1: [SKIP] Skip running #<CALL-TASK :FUNC #<CLOSURE (LAMBDA ()
                                           :IN
                                           CL-BODGE.ENGINE:INITIALIZE-SYSTEM) {1005353F3B}> :STATUS :RUNNING {10054C08D3}>
 2: [ABORT] Stop the runner #<QUEUED-RUNNER :STATUS :RUNNING {100170F8E3}> entirely.
 3: [STOP-RUNNER] Stop the runner #<QUEUED-RUNNER :STATUS :RUNNING {100170F8E3}> entirely.

Backtrace:
 7: (SB-KERNEL::%SIGNAL NSGL: Failed to find a suitable pixel format)
 8: (ERROR NSGL: Failed to find a suitable pixel format)
 9: ((LAMBDA (#:|error-code0| CL-GLFW3::MESSAGE) :IN "/Users/travis/quicklisp/dists/quicklisp/software/cl-glfw3-20171019-git/cl-glfw3.lisp") #<unused argument> #.(SB-SYS:INT-SAP #X011FBFA0))
 10: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/Users/travis/quicklisp/dists/quicklisp/software/cl-glfw3-20171019-git/cl-glfw3.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
 11: ("foreign function: funcall_alien_callback")
 12: ("foreign function: #x20100387")
 13: ("foreign function: #x5C31241E2A1F0072")
 14: ("foreign function: _glfwCreateContextNSGL")
 15: ("foreign function: _glfwPlatformCreateWindow")
 16: ("foreign function: glfwCreateWindow")
 17: (%CL-GLFW3:CREATE-WINDOW 640 480 Scene #.(SB-SYS:INT-SAP #X00000000) #.(SB-SYS:INT-SAP #X00000000))
 18: (CL-GLFW3:CREATE-WINDOW WIDTH 640 HEIGHT 480 TITLE Scene MONITOR NIL SHARED NIL RESIZABLE NIL VISIBLE T DECORATED T RED-BITS 8 GREEN-BITS 8 BLUE-BITS 8 ALPHA-BITS 8 DEPTH-BITS 24 STENCIL-BITS 8 ACCUM-RED-BITS 0 ACCUM-GREEN-BITS 0 ACCUM-BLUE-BITS 0 ACCUM-ALPHA-BITS 0 AUX-BUFFERS 0 SAMPLES 0 REFRESH-RATE 0 STEREO NIL SRGB-CAPABLE NIL CLIENT-API OPENGL-API CONTEXT-VERSION-MAJOR 3 CONTEXT-VERSION-MINOR 3 CONTEXT-ROBUSTNESS NO-ROBUSTNESS OPENGL-FORWARD-COMPAT T OPENGL-DEBUG-CONTEXT NIL OPENGL-PROFILE OPENGL-CORE-PROFILE)
 19: ((LAMBDA NIL :IN CL-BODGE.ENGINE:INITIALIZE-SYSTEM))
Unhandled SIMPLE-CONDITION in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                        {1003520083}>:
  SIMPLE-ERROR: NSGL: Failed to find a suitable pixel format

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1003520083}>
0: ("bogus stack frame")
1: (SB-UNIX:NANOSLEEP 0 65536000)
2: (SB-IMPL::%%WAIT-FOR #<CLOSURE (FLET SB-THREAD::WAKEUP :IN SB-THREAD::%CONDITION-WAIT) {11FF7BB}> NIL NIL)
3: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::%CONDITION-WAIT))
4: (SB-THREAD:CONDITION-WAIT #<SB-THREAD:WAITQUEUE latch-state {100459A613}> #<SB-THREAD:MUTEX "latch-lock" (free)> :TIMEOUT NIL)
5: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CL-MUTH:WAIT-FOR-LATCH))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
7: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN CL-MUTH:WAIT-FOR-LATCH) {11FFC2B}> #<SB-THREAD:MUTEX "latch-lock" (free)> T NIL)
8: (CL-MUTH:WAIT-FOR-LATCH #<CL-MUTH::SIMPLE-LATCH {100459A5D3}>)
9: (CL-BODGE.ENGINE:STARTUP (:ENGINE (:SYSTEMS (NOTALONE::NOTALONE) :LOG-LEVEL :INFO) :HOST (:OPENGL-VERSION (3 3))) "/Users/priyadarshan/Downloads/notalone/./")
10: (TRIVIAL-GAMEKIT:START NOTALONE::NOTALONE :LOG-LEVEL :INFO :OPENGL-VERSION (3 3) :BLOCKING T)
11: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
12: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1003583E1B}>)
13: ((FLET "WITHOUT-INTERRUPTS-BODY-36" :IN SAVE-LISP-AND-DIE))
14: ((LABELS SB-IMPL::RESTART-LISP :IN SAVE-LISP-AND-DIE))

unhandled condition in --disable-debugger mode, quitting
```

**Comment by borodust** [comment]
Unfortunately, that most likely means that `macOS` in VirtualBox VM doesn't support OpenGL 3.3 which is required to run the game :(

**Comment by priyadarshan** [comment]
I am sorry I can't be more useful! I just can't upgrade the physical OS X I have, it would affects a few key apps I rely upon for work.

**Comment by borodust** [comment]
No probs! Thanks a lot for the tests! I'm closing this issue though. I'm quite convinced original error was due unsupported/old `macOS` version.
